#!/bin/sh
#
# bootstrap installs things.

# Assume everyone's on OS X and run Homebrew (*nix-ers beware)
if [ $(uname -s) = "Darwin" ] 
then
	. script/homebrew
fi

# Run the install (I'd like to pull this out of rake, eventually)
rake install

cd /Applications && curl http://www.ninjamonkeysoftware.com/slate/versions/slate-latest.tar.gz | tar -xz

